### ISSUE TITLE
[Feature Request]: Environment variables for Apollo Vampire Accelerators.

### ISSUE THREAD

**Issue by Tallguy298** [larsonmars/sysvars#6]
Could you please add the following variables to your next release, Vampire Core Revision and Vampire Version?
Information is here ... http://www.apollo-core.com/index.htm?page=coding&tl=2
Vampire Core Revision is at address 0xDFF3EA & Vampire Version is at address 0xDFF3FC.

I am still learning how to code and this would help.

Thank you.

**Comment by larsonmars** [comment]
> Could you please add the following variables to your next release, Vampire Core Revision and Vampire Version? Information is here ... http://www.apollo-core.com/index.htm?page=coding&tl=2 Vampire Core Revision is at address 0xDFF3EA & Vampire Version is at address 0xDFF3FC.
> 
> I am still learning how to code and this would help.
> 
> Thank you.

I have glanced over the documentation you provided. Are you sure that Core Revision is actually implemented? The documentation says "Reserved", which usually indicates that it is not. Also, there is no further information behind it (in contrast to the other items).

The Vampire Version (0xDFF3FC) I can do, but someone with an actual Vampire would have to test it.

**Comment by Tallguy298** [comment]
Thursday, 10 October 2024

8:06:30 AM

 

Hi Larson,

Yes the core revision is actually implemented.

I have peeked at address 0xDFF3EA (Core Revision) using the APEEK command (http://aminet.net/util/shell/APeek.lha) and the value returned is the current flashed firmware .jic file for my Amiga Manticore accelerator.

The vampire core version is not necessary.
Some beta test cores give a 0 or -1 result in the Core Revision.

So ideally the VCoreRev environment variable would have the 16-bit core revision or “N/A” if 0 or -1.

I can test this quite easily.

 

Thank you,

Alexander.

**Comment by larsonmars** [comment]
> So ideally the VCoreRev environment variable would have the 16-bit core revision or “N/A” if 0 or -1.

Sounds reasonable.

Currently, my time is quite sparse, but I will see what I can do. Thank you for taking the risk to be the volunteer tester 😄

**Comment by larsonmars** [comment]
Can you please test the appended version?
[sysvars.zip](https://github.com/user-attachments/files/17356726/sysvars.zip)

**Comment by Tallguy298** [comment]
Didn't work.
The variables VampireCoreRev, VampireType, VampireClockMult were not created.
To check if the core revision was in address $dff3ea I ran this utility.
[Quick_080_chk.zip](https://github.com/user-attachments/files/17357802/Quick_080_chk.zip)

Regards,
Alex.

**Comment by larsonmars** [comment]
Are you sure you have the last version?

**Comment by Tallguy298** [comment]
Here are the my results...

[SysVars_Results.zip](https://github.com/user-attachments/files/17357886/SysVars_Results.zip)

Regards,
Alex.

**Comment by larsonmars** [comment]
Can you please peek at 0xdff3fc (Version)
Is the core rev correct? If not, what is expected and can you also give the peek?

**Comment by Tallguy298** [comment]
The core revision displayed should be 10370.

Regards,
Alex.

**Comment by larsonmars** [comment]
Ok, didnt know the numbers get this big. My print routine only handles 4 chars atm. Can you give the Vampire Version peek?

**Comment by Tallguy298** [comment]
Here are the results...

`[00] $00DFF3EA: $2882  10370`
`[00] $00DFF3FC: $070D   1805`

Regards,
Alex.

**Comment by larsonmars** [comment]
Ok I adapted the number printing routine (which was originally only meant for version strings) and fixed the offset for the constants. Can you check?

[sysvars.zip](https://github.com/user-attachments/files/17369693/sysvars.zip)

**Comment by Tallguy298** [comment]
Works beautifully.
Here are the results from the cli SET command...

`BSDSockLib                 `
`BSDSockLibRev              `
`BSDSockLibVer              `
`Chipset           SAGA     `
`CPU               68080    `
`FPU               68882    `
`KickRev           111      `
`KickVer           47       `
`process           2        `
`RC                0        `
`Result2           0        `
`UAEMajor                   `
`UAEMinor                   `
`UAERev                     `
`VampireClockMult  13       `
`VampireCoreRev    10370    `
`VampireType       V4_600   `
`VFreq             60       `
`VIEWER            MULTIVIEW`

Thank you very much...
Regards,
Alexander.
