### ISSUE TITLE
Vampire variables are not set.

### ISSUE THREAD

**Issue by Tallguy298** [larsonmars/sysvars#8]
Installed your new 0.14 version.
Variables - $VampireType, $VampireCoreRev and $VampireClockMult are not set.
I am running Workbench 3.2.2, Kickstart 3.2.2 on Amiga MantiCore v4.
The previous version 0.13 the variables were set. 

This is the output from the SET command.
`Chipset           SAGA     `
`CPU               68080    `
`FPU               internal `
`KickRev           111      `
`KickVer           47       `
`process           2        `
`RC                0        `
`Result2           0        `
`TotalChipRam      6144     `
`TotalFastRam      499712   `
`TotalSlowRam      1536     `
`VFreq             60       `
`VIEWER            MULTIVIEW`

Thank you...
Alexander.

**Comment by larsonmars** [comment]
Hi Alexander,

thank you very much for reporting! The only thing I cannot test here... But I think I found it, a simple typo (function is named seVampireEnvVars, instead of setVampireEnvVars...). I'll fix it and post a version for you to test.

Best regards,

Lars

**Comment by larsonmars** [comment]
Can you please test this?

[sysvars.zip](https://github.com/user-attachments/files/17737966/sysvars.zip)

**Comment by Tallguy298** [comment]
HI Lars,
SET command results...
`Chipset           SAGA     `
`CPU               68080    `
`FPU               internal `
`KickRev           111      `
`KickVer           47       `
`process           2        `
`RC                0        `
`Result2           0        `
`TotalChipRam      6144     `
`TotalFastRam      499712   `
`TotalRam          507392   `
`TotalSlowRam      1536     `
`VampireClockMult  13       `
`VampireCoreRev    10418    `
`VampireType       Unknown  `
`VFreq             60       `
`VIEWER            MULTIVIEW`


My MantiCore v4 card shows as being unknown.
It should be type 7 - V4_600.

Thanks,
Alexander.

**Comment by larsonmars** [comment]
This is the beauty of well-documented open source. You can fix it yourself if the dev makes stupid mistakes.

D4 works, because D0-D3 is actually overwritten by the SET_ENV macro (I should read my own documentation). I will put a comment there to prevent anyone in the future from changing it to any of those registers.

Thanks for spotting, new release underway.
